HF_TOKEN = "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"
GROQ_API_KEY="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"
TAVILY_API_KEY="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"
SERPER_API_KEY="ad31943073959beedaa58d6bc15c8d16cd572204"