anime = "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"
GROQ_API_KEY="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"
TAVILY_API_KEY="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"
SERPER_API_KEY="ad31943073959beedaa58d6bc15c8d16cd572204"